import React, { useState } from 'react';
import { formatCurrency } from '../utils/promptBuilder';

function ExportModal({ isOpen, onClose, result, taxYear, profile }) {
    const [exporting, setExporting] = useState(false);
    const [exportFormat, setExportFormat] = useState('clipboard');

    if (!isOpen || !result) return null;

    const generateTextReport = () => {
        const { income, deductions, calculation, summary } = result;
        const lines = [
            '═══════════════════════════════════════════════════════════════',
            '                    TAXMINI - TAX SUMMARY REPORT',
            '═══════════════════════════════════════════════════════════════',
            '',
            `Tax Year: ${taxYear}`,
            `Generated: ${new Date().toLocaleDateString('de-DE')}`,
            '',
            '───────────────────────────────────────────────────────────────',
            '                          SUMMARY',
            '───────────────────────────────────────────────────────────────',
            '',
            summary || 'No summary available.',
            '',
            '───────────────────────────────────────────────────────────────',
            '                          INCOME',
            '───────────────────────────────────────────────────────────────',
            '',
            `  Gross Salary (Bruttolohn):     ${formatCurrency(income?.grossSalary || 0)}`,
            `  Tax Paid (Lohnsteuer):         ${formatCurrency(income?.taxPaid || 0)}`,
            `  Church Tax (Kirchensteuer):    ${formatCurrency(income?.churchTax || 0)}`,
            `  Solidarity Surcharge:          ${formatCurrency(income?.solidaritySurcharge || 0)}`,
            '',
            '  Social Security:',
            `    - Health Insurance:          ${formatCurrency(income?.socialSecurity?.health || 0)}`,
            `    - Pension Insurance:         ${formatCurrency(income?.socialSecurity?.pension || 0)}`,
            `    - Unemployment Insurance:    ${formatCurrency(income?.socialSecurity?.unemployment || 0)}`,
            `    - Care Insurance:            ${formatCurrency(income?.socialSecurity?.care || 0)}`,
            '',
            '───────────────────────────────────────────────────────────────',
            '                        DEDUCTIONS',
            '───────────────────────────────────────────────────────────────',
            '',
            `  Home Office:                   ${formatCurrency(deductions?.homeOffice?.amount || 0)}`,
            `  Commuting (Pendlerpauschale):  ${formatCurrency(deductions?.commuting?.amount || 0)}`,
            `  Work Equipment:                ${formatCurrency(deductions?.workEquipment?.amount || 0)}`,
            `  Professional Development:      ${formatCurrency(deductions?.professionalDevelopment?.amount || 0)}`,
            `  Other Deductions:              ${formatCurrency(deductions?.other?.amount || 0)}`,
            '  ─────────────────────────────────────────────────────────────',
            `  TOTAL DEDUCTIONS:              ${formatCurrency(deductions?.totalDeductions || 0)}`,
            '',
            '───────────────────────────────────────────────────────────────',
            '                       TAX CALCULATION',
            '───────────────────────────────────────────────────────────────',
            '',
            `  Taxable Income:                ${formatCurrency(calculation?.taxableIncome || 0)}`,
            `  Expected Tax:                  ${formatCurrency(calculation?.expectedTax || 0)}`,
            `  Tax Already Paid:              ${formatCurrency(calculation?.taxAlreadyPaid || 0)}`,
            '',
            '═══════════════════════════════════════════════════════════════',
            calculation?.estimatedRefund >= 0
                ? `  ESTIMATED REFUND:              +${formatCurrency(calculation?.estimatedRefund || 0)}`
                : `  ESTIMATED TAX DUE:             ${formatCurrency(Math.abs(calculation?.estimatedRefund || 0))}`,
            '═══════════════════════════════════════════════════════════════',
            '',
            '⚠️  DISCLAIMER: This is an estimate only.',
            '    For official filing, use ELSTER or consult a Steuerberater.',
            '',
            '    Generated by TaxMini - Privacy-First German Tax Assistant',
            '',
        ];
        return lines.join('\n');
    };

    const handleExport = async () => {
        setExporting(true);
        const report = generateTextReport();

        try {
            if (exportFormat === 'clipboard') {
                await navigator.clipboard.writeText(report);
                alert('Report copied to clipboard!');
            } else if (exportFormat === 'download') {
                const blob = new Blob([report], { type: 'text/plain;charset=utf-8' });
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `TaxMini-Report-${taxYear}.txt`;
                document.body.appendChild(a);
                a.click();
                document.body.removeChild(a);
                URL.revokeObjectURL(url);
            }
            onClose();
        } catch (error) {
            alert('Export failed: ' + error.message);
        } finally {
            setExporting(false);
        }
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm">
            <div className="bg-dark-800 rounded-2xl border border-dark-600 shadow-2xl w-full max-w-md mx-4 overflow-hidden animate-scale-in">
                {/* Header */}
                <div className="p-6 border-b border-dark-600">
                    <div className="flex items-center justify-between">
                        <h2 className="text-xl font-bold text-text-primary">Export Report</h2>
                        <button
                            onClick={onClose}
                            className="p-2 rounded-lg hover:bg-dark-700 text-text-muted hover:text-text-primary transition-colors"
                        >
                            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                            </svg>
                        </button>
                    </div>
                    <p className="text-sm text-text-muted mt-1">
                        Save your tax summary for your records
                    </p>
                </div>

                {/* Content */}
                <div className="p-6 space-y-4">
                    {/* Format selection */}
                    <div className="space-y-3">
                        <label className="block text-sm font-medium text-text-secondary">
                            Export Format
                        </label>
                        <div className="grid grid-cols-2 gap-3">
                            <button
                                onClick={() => setExportFormat('clipboard')}
                                className={`p-4 rounded-xl border-2 text-left transition-all ${exportFormat === 'clipboard'
                                        ? 'border-accent-primary bg-accent-primary/10'
                                        : 'border-dark-600 bg-dark-700 hover:border-dark-500'
                                    }`}
                            >
                                <span className="text-2xl">📋</span>
                                <span className="block font-medium mt-2">Clipboard</span>
                                <span className="block text-xs text-text-muted">Copy to paste anywhere</span>
                            </button>
                            <button
                                onClick={() => setExportFormat('download')}
                                className={`p-4 rounded-xl border-2 text-left transition-all ${exportFormat === 'download'
                                        ? 'border-accent-primary bg-accent-primary/10'
                                        : 'border-dark-600 bg-dark-700 hover:border-dark-500'
                                    }`}
                            >
                                <span className="text-2xl">💾</span>
                                <span className="block font-medium mt-2">Download</span>
                                <span className="block text-xs text-text-muted">Save as .txt file</span>
                            </button>
                        </div>
                    </div>

                    {/* Preview */}
                    <div>
                        <label className="block text-sm font-medium text-text-secondary mb-2">
                            Preview
                        </label>
                        <pre className="p-3 bg-dark-900 rounded-lg text-xs text-text-muted font-mono max-h-32 overflow-y-auto">
                            {generateTextReport().slice(0, 500)}...
                        </pre>
                    </div>
                </div>

                {/* Footer */}
                <div className="p-6 border-t border-dark-600 flex gap-3">
                    <button
                        onClick={onClose}
                        className="flex-1 btn btn-secondary"
                    >
                        Cancel
                    </button>
                    <button
                        onClick={handleExport}
                        disabled={exporting}
                        className="flex-1 btn btn-primary"
                    >
                        {exporting ? 'Exporting...' : exportFormat === 'clipboard' ? 'Copy to Clipboard' : 'Download File'}
                    </button>
                </div>
            </div>
        </div>
    );
}

export default ExportModal;
